#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: tehopanas/cs3219-api-gateway:latest
        env:
          - name: USER_SERVICE_URL
            value: http://user-service.default.svc.cluster.local:3001
          - name: QUESTION_SERVICE_URL
            value: http://question-service.default.svc.cluster.local:3002
          - name: CODE_EXECUTION_SERVICE_URL
            value: http://code-execution-service.default.svc.cluster.local:3005
          - name: COLLABORATION_SERVICE_URL
            value: http://collaboration-service.default.svc.cluster.local:3004
          - name: MATCHING_SERVICE_URL
            value: http://matching-service.default.svc.cluster.local:3006
          - name: PORT
            value: "3003"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3003


---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - port: 3003
    targetPort: 3003
    
  

